"""Restructure core tables

Revision ID: bf9e3bafda9b
Revises: bd76b1b79145
Create Date: 2025-09-27 20:36:01.016507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf9e3bafda9b'
down_revision = 'bd76b1b79145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('subtotal')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))

    with op.batch_alter_table('mpesa_callbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('result_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('result_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_date', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('transaction_id'))
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('status')
        batch_op.drop_column('raw_callback')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('phone_number'))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('phone_number')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('phone_number'), ['phone_number'], unique=True)
        batch_op.drop_column('role')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    with op.batch_alter_table('mpesa_callbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_callback', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index(batch_op.f('transaction_id'), ['transaction_id'], unique=True)
        batch_op.drop_column('transaction_date')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('result_desc')
        batch_op.drop_column('result_code')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('merchant_request_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('stock')
        batch_op.drop_column('description')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', mysql.FLOAT(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('total')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
